name: Update M3U File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Script to Update M3U
        run: python process_m3u.py  # Runs script to update the M3U file

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add updated.m3u
          git commit -m "Auto-update M3U file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
